[metadata]
name = "Oceanic Eyes"
author = "Yi Hyunjoon"
version = "0.1.0"

[colors]

[colors.primary]
background = "#13181b"
foreground = "#d8dee9"

[colors.normal]
black = "#13181b"
red = "#ec5f67"
green = "#99c794"
yellow = "#fac863"
blue = "#6699cc"
magenta = "#c594c5"
cyan = "#5fb3b3"
white = "#a7adba"

[colors.bright]
black = "#343d46"
red = "#ec5f67"
green = "#99c794"
yellow = "#fac863"
blue = "#6699cc"
magenta = "#c594c5"
cyan = "#5fb3b3"
white = "#d8dee9"
